import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Logo from "../public/jordanLogo.png"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/jordanLogo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow&display=swap"
          rel="stylesheet"
        />

      </Head>
      <main >
        <div className={styles.container}>
          <div className={styles.circle}>
            <Image src={Logo} alt='hi' height={400} width={400} className={styles.logo} />
            <div className={styles.innerlink}>
              <div>
                <Link href={"/about"}>
                  About
                </Link>
              </div>
            </div>
            <div className={styles.innerlink}>
              <Link href={"/projects"}>
                Projects
              </Link>
            </div>
            <div className={styles.innerlink}>
              <div>
                Contact
              </div>
            </div>
            <div className={styles.innerlink}>
              <div>
                Stuff
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
